### ISSUE TITLE
Warna dominan pada toko onlinenya?

### ISSUE THREAD

**Issue by sektibayu** [muhrifat/online-shop#1]
halo teman-teman saya mau menanyakan apakah warna dominan yang akan kita buat untuk toko online kalian? terimakasih

**Comment by muhrifat** [comment]
@niakurniam dkk ..

**Comment by niakurniam** [comment]
warna dominan coklat pohon mungkin @sektibayu

**Comment by niakurniam** [comment]
kan, ini ntar fokusannya online shop pakaian khusus cowok. pokoknya warna yang emang cocok buat cowok

**Comment by muhrifat** [comment]
Oke ntar tak post, coba dikomen yak ..
\
