### ISSUE TITLE
Dasboard admin

### ISSUE THREAD

**Issue by sektibayu** [muhrifat/online-shop#4]
bagaimana isi dari dasboard admin ditiadakan atau mending langsung laporan Penjualan saja?

**Comment by niakurniam** [comment]
@elvamaulidiah97

**Comment by elvamaulidiah97** [comment]
Kalo lebih baiknya tetap ada report penjualan

**Comment by muhrifat** [comment]
jadi nambah requirement ya rek, report penjualan? 
- [ ] report pengunjung, 
- [ ] barang terjual, 
- [ ] report pembeli cukup yak

semangat pembuat admin @sektibayu 👍

**Comment by muhrifat** [comment]
@elvamaulidiah97 @niakurniam @hendradn

**Comment by niakurniam** [comment]
report pembeli bentuk grafik aja @sektibayu @muhrifat

**Comment by niakurniam** [comment]
semuanya bentuk grafik aja report nya biar gak susah @sektibayu @muhrifat

**Comment by sektibayu** [comment]
ok report bentuk grafik saja ya

**Comment by niakurniam** [comment]
tapi untuk di dashboard tampilkan angka bulan ini saja @sektibayu @muhrifat

**Comment by sektibayu** [comment]
ok sep dikerjakan

**Comment by muhrifat** [comment]
💯
