### ISSUE TITLE
Kekurangan

### ISSUE THREAD

**Issue by elvamaulidiah97** [muhrifat/online-shop#7]
Detail barang dan Admin kurang tombol Delete
untuk pesanan  tambahkan tombol confirm, kolom status, dan kolom tanggal pembayaran

**Comment by sektibayu** [comment]
Ok va dikerjakan

**Comment by niakurniam** [comment]
rek, gak usah ada size sama color. karena kita olshop yg unik

**Comment by sektibayu** [comment]
ok kur
